package itrace

func GetComponentName(i int) string {
	return componentName[i]
}

var componentName = map[int]string{
	ComponentUnknown:              "Unknown",
	ComponentTomcat:               "Tomcat",
	ComponentHttpClient:           "HttpClient",
	ComponentDubbo:                "Dubbo",
	ComponentH2:                   "H2",
	ComponentMysql:                "Mysql",
	ComponentORACLE:               "ORACLE",
	ComponentRedis:                "Redis",
	ComponentMotan:                "Motan",
	ComponentMongoDB:              "MongoDB",
	ComponentResin:                "Resin",
	ComponentFeign:                "Feign",
	ComponentOKHttp:               "OKHttp",
	ComponentSpringRestTemplate:   "SpringRestTemplate",
	ComponentSpringMVC:            "SpringMVC",
	ComponentStruts2:              "Struts2",
	ComponentNutzMVC:              "NutzMVC",
	ComponentNutzHttp:             "NutzHttp",
	ComponentJettyClient:          "JettyClient",
	ComponentJettyServer:          "JettyServer",
	ComponentMemcached:            "Memcached",
	ComponentShardingJDBC:         "ShardingJDBC",
	ComponentPostgreSQL:           "PostgreSQL",
	ComponentGRPC:                 "GRPC",
	ComponentElasticJob:           "ElasticJob",
	ComponentRocketMQ:             "RocketMQ",
	ComponentHttpasyncclient:      "Httpasyncclient",
	ComponentKafka:                "Kafka",
	ComponentServiceComb:          "ServiceComb",
	ComponentHystrix:              "Hystrix",
	ComponentJedis:                "Jedis",
	ComponentSQLite:               "SQLite",
	ComponentH2JdbcDriver:         "H2JdbcDriver",
	ComponentMysqlConnectorJava:   "MysqlConnectorJava",
	ComponentOjdbc:                "Ojdbc",
	ComponentSpymemcached:         "Spymemcached",
	ComponentXmemcached:           "Xmemcached",
	ComponentPostgresqlJdbcDriver: "PostgresqlJdbcDriver",
	ComponentRocketMQProducer:     "RocketMQProducer",
	ComponentRocketMQConsumer:     "RocketMQConsumer",
	ComponentKafkaProducer:        "KafkaProducer",
	ComponentKafkaConsumer:        "KafkaConsumer",
	ComponentMongodbDriver:        "MongodbDriver",
	ComponentSOFARPC:              "SOFARPC",
	ComponentActiveMQ:             "ActiveMQ",
	ComponentActivemqProducer:     "ActivemqProducer",
	ComponentActivemqConsumer:     "ActivemqConsumer",
	ComponentElasticsearch:        "Elasticsearch",
	ComponentTransportClient:      "TransportClient",
	ComponentHttp:                 "Http",
	ComponentRpc:                  "Rpc",
	ComponentRabbitMQ:             "RabbitMQ",
	ComponentRabbitmqProducer:     "RabbitmqProducer",
	ComponentRabbitmqConsumer:     "RabbitmqConsumer",
	ComponentCanal:                "Canal",
	ComponentGson:                 "Gson",
	ComponentRedisson:             "Redisson",
	ComponentLettuce:              "Lettuce",
	ComponentZookeeper:            "Zookeeper",
	ComponentVertx:                "Vertx",
	ComponentShardingSphere:       "ShardingSphere",
	ComponentSpringCloudGateway:   "SpringCloudGateway",
	ComponentRESTEasy:             "RESTEasy",
	ComponentSolrJ:                "SolrJ",
	ComponentSolr:                 "Solr",
	ComponentSpringAsync:          "SpringAsync",
	ComponentJdkHttp:              "JdkHttp",
	ComponentSpringWebflux:        "SpringWebflux",
	ComponentPlay:                 "Play",
	ComponentCassandraJavaDriver:  "CassandraJavaDriver",
	ComponentCassandra:            "Cassandra",
	ComponentLight4J:              "Light4J",
	ComponentPulsar:               "Pulsar",
	ComponentPulsarProducer:       "PulsarProducer",
	ComponentPulsarConsumer:       "PulsarConsumer",
	ComponentEhcache:              "Ehcache",
	ComponentSocketIO:             "SocketIO",
	ComponentRestHighLevelClient:  "RestHighLevelClient",
	ComponentSpringTx:             "SpringTx",
	ComponentArmeria:              "Armeria",
	ComponentJdkThreading:         "JdkThreading",
	ComponentKotlinCoroutine:      "KotlinCoroutine",
	ComponentAvroServer:           "AvroServer",
	ComponentAvroClient:           "AvroClient",
	ComponentUndertow:             "Undertow",
	ComponentFinagle:              "Finagle",
	ComponentMariadb:              "Mariadb",
	ComponentMariadbJdbc:          "MariadbJdbc",
	ComponentQuasar:               "Quasar",
	ComponentInfluxDB:             "InfluxDB",
	ComponentInfluxdbJava:         "InfluxdbJava",
	ComponentBrpcJava:             "BrpcJava",
	ComponentGraphQL:              "GraphQL",

	// C# .NET
	ComponentAspNetCore:                          "AspNetCore",
	ComponentEntityFrameworkCore:                 "EntityFrameworkCore",
	ComponentSqlClient:                           "SqlClient",
	ComponentCAP:                                 "CAP",
	ComponentStackExchangeRedis:                  "StackExchangeRedis",
	ComponentSqlServer:                           "SqlServer",
	ComponentNpgsql:                              "Npgsql",
	ComponentMySqlConnector:                      "MySqlConnector",
	ComponentEntityFrameworkCoreInMemory:         "EntityFrameworkCoreInMemory",
	ComponentEntityFrameworkCoreSqlServer:        "EntityFrameworkCoreSqlServer",
	ComponentEntityFrameworkCoreSqlite:           "EntityFrameworkCoreSqlite",
	ComponentPomeloEntityFrameworkCoreMySql:      "PomeloEntityFrameworkCoreMySql",
	ComponentNpgsqlEntityFrameworkCorePostgreSQL: "NpgsqlEntityFrameworkCorePostgreSQL",
	ComponentInMemoryDatabase:                    "InMemoryDatabase",
	ComponentAspNet:                              "AspNet",
	ComponentSmartSql:                            "SmartSql",

	// NoeJS components
	// [4000, 5000) for Node.js agent
	ComponentHttpServer: "HttpServer",
	ComponentExpress:    "Express",
	ComponentEgg:        "Egg",
	ComponentKoa:        "Koa",

	// Golang components
	// [5000, 6000) for Golang agent
	ComponentServiceCombMesher:        "ServiceCombMesher",
	ComponentServiceCombServiceCenter: "ServiceCombServiceCenter",
	ComponentMOSN:                     "MOSN",
	ComponentGoHttpServer:             "GoHttpServer",
	ComponentGoHttpClient:             "GoHttpClient",
	ComponentGin:                      "Gin",
	ComponentGear:                     "Gear",

	// Lua
	ComponentNginx: "Nginx",

	ComponentPython:   "Python",
	ComponentFlask:    "Flask",
	ComponentRequests: "Requests",

	//PHP
	ComponentPHP:    "PHP",
	ComponentCURL:   "CURL",
	ComponentPDO:    "PDO",
	ComponentMysqli: "Mysqli",
	ComponentYar:    "Yar",
	ComponentPredis: "Predis",
}
